general:
  project_name: COL788
  logs_dir: logs
  saved_models_dir: saved_models

dataset:
  name: custom
  class_names: ['dog', 'chainsaw', 'crackling_fire', 'car_horn', 'rain',
    'crying_baby', 'clock_tick', 'sneezing', 'rooster', 'sea_waves']
  audio_path: ../training/datasets/ESC-50/audio
  csv_path: ../training/datasets/ESC-50/meta/esc50.csv
  file_extension: .wav
  validation_split: 0.1
  test_split : 0.2
  test_path: 
  use_other_class: False
  n_samples_per_other_class: 2

dataset_specific:
# Contains dataset-specific parameters.
  fsd50k:
    csv_folder: ../training/datasets/FSD50K/FSD50K.ground_truth
    dev_audio_folder: ../training/datasets/FSD50K/FSD50K.dev_audio
    eval_audio_folder: ../training/datasets/FSD50K/FSD50K.eval_audio
    audioset_ontology_path: ../utils/dataset_utils/fsd50k/audioset_ontology.json
    only_keep_monolabel: True


pre_processing:
  min_length: 1
  max_length : 10
  target_rate: 16000
  top_db: 30
  frame_length: 3200
  hop_length: 3200
  trim_last_second: False
  lengthen : 'after'

feature_extraction:
  patch_length: 96
  n_mels: 64
  overlap: 0.25
  n_fft: 512
  hop_length: 160
  window_length: 400
  window: hann
  center: False
  pad_mode: constant
  power: 1.0
  fmin: 125
  fmax: 7500
  norm: None
  htk : True
  to_db : False
  include_last_patch: False

model:
  model_type: {name : yamnet, embedding_size: 256}
  # Shape of a single patch.
  # Input shape must be [mels, frames]
  input_shape: [64, 96]
  expand_last_dim: True
  multi_label : False
  # model_path: ..\..\models\yamnet\ST_pretrainedmodel_public_dataset\esc_10\yamnet_256_64x96\yamnet_256_64x96_int8.tflite
  model_path: ../training/outputs/2023_10_03_19_27_00/quantized_models/quantized_model.tflite
  unknown_class_threshold: 0.0

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  c_project_path: ../../getting_started/threadx # Change to ../../getting_started/threadx to use threadx version
  serie: STM32L4
  IDE: GCC
  verbosity: 1
  version: 8.1.0
  optimization: balanced
  footprints_on_target: STEVAL-STLCS01V1
  path_to_stm32ai: /home/srijan/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/8.1.0/Utilities/linux/stm32ai
  path_to_cubeIDE: /opt/st/stm32cubeide_1.13.2/stm32cubeide

  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
